BUG: Update units specification in ConvertTiffFile.ipynb
Addresses:

```
axis_units = { d:str(getattr(ome.images[0].pixels, f"physical_size_{d}_quantity").units) for d in dims}
axis_units
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [10], line 1
----> 1 axis_units = { d:str(getattr(ome.images[0].pixels, f"physical_size_{d}_quantity").units) for d in dims}
      2 axis_units

Cell In [10], line 1, in <dictcomp>(.0)
----> 1 axis_units = { d:str(getattr(ome.images[0].pixels, f"physical_size_{d}_quantity").units) for d in dims}
      2 axis_units

File ~/bin/mambaforge/envs/spatial-image/lib/python3.9/site-packages/ome_types/_mixins/_base_type.py:177, in OMEType.__getattr__(self, key)
    170     warnings.warn(
    171         f"Attribute '{cls_name}.{key}' is deprecated, use {new_key!r} instead",
    172         DeprecationWarning,
    173         stacklevel=2,
    174     )
    175     return getattr(self, new_key)
--> 177 return super().__getattr__(key)

AttributeError: 'super' object has no attribute '__getattr__'
```

ome.types does not contain the correspond entry anymore. Manually add the 'micrometer' unit, identified in the OME XML metadata print out in an earlier cell in the format specified by OME-Zarr.